#### Excellent Tutorials Series (ETS)
#### Author: Thomas K Torku
#### Topic: Overview 

### Introduction to Numpy

`Numpy:` It is a module in python used for multipurpose functionalities
 - N-dimensional array
 - Used for function broadcasting
 - Use for linear algebra, statistics, geometry, trig etc..

In [1]:
# from numpy import *
# from numpy import *
import numpy as np

In [2]:
def arr_lis(n):
    arr=[]
    for i in range(n):
        arr.append([int(x) for x in input().split()]) #list comprehension
    return arr

In [3]:
arr_lis(2)

 2 3
 4 5


[[2, 3], [4, 5]]

In [4]:
arr =np.array([[1,2],[3, 4]])

In [5]:
arr

array([[1, 2],
       [3, 4]])

In [6]:
type(arr)

numpy.ndarray

In [7]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [8]:
arr1=np.arange(0,5.1, 0.2)
arr1

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ])

In [9]:
arr1.shape

(26,)

In [10]:
np.linspace(0,5,25)

array([0.        , 0.20833333, 0.41666667, 0.625     , 0.83333333,
       1.04166667, 1.25      , 1.45833333, 1.66666667, 1.875     ,
       2.08333333, 2.29166667, 2.5       , 2.70833333, 2.91666667,
       3.125     , 3.33333333, 3.54166667, 3.75      , 3.95833333,
       4.16666667, 4.375     , 4.58333333, 4.79166667, 5.        ])

In [11]:
np.zeros((10, 10), dtype=float)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [12]:
u =np.zeros(5)
print(u)
# n =len(u)
# uz =np.arange(n)
# print(uz)
# for i in range(n):
#     u[i] =uz[i]
# print(u)    

[0. 0. 0. 0. 0.]


In [13]:
n=len(u)
n

5

In [14]:
uz =np.arange(n)
print(uz)

[0 1 2 3 4]


In [15]:
for i in range(n):
    u[i]=uz[i]
print(u)

[0. 1. 2. 3. 4.]


In [16]:
### create an empty array of zeros of size 10 and replace to numbers

In [17]:
print(np.__version__)

1.19.2


In [18]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
arr2 =np.array([1, 2, 3,4, 5,6, 7, 8,9,10, 11])

In [20]:
odd= arr2[arr2%2==1]

In [21]:
odd

array([ 1,  3,  5,  7,  9, 11])

In [22]:
## Create an 1D array of size 40 and print all the even numbers and odd numbers

In [23]:
even =arr2[arr2%2==0]
even

array([ 2,  4,  6,  8, 10])

### Resizing Arrays

In [24]:
##Use the reshape()
arr2.shape    #1D array

(11,)

In [25]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
## 2D
arr3 =arr2.reshape((-1, 1))

In [27]:
arr3.shape

(11, 1)

In [28]:
arr3

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [29]:
art =np.array([1, 2,3, 4,5, 9, 10, 11, 6,8])

arr4 =art.reshape((-1,2))
arr4.shape

(5, 2)

### Stacking Arrays together

In [30]:
els= np.array([1,2,3,4,5,6])
els.shape

(6,)

In [31]:
els1 =els.reshape((-1,1))
els1.shape

(6, 1)

In [32]:
els2 =els.reshape((-1,3))
els2.shape

(2, 3)

In [33]:
a1 =np.arange(9).reshape((-1,1))
a2 =np.array([-1, 0, 2, 3, 4, 5, -2, -3, 5]).reshape((-1,1))

In [34]:
a2.shape

(9, 1)

In [35]:
v =np.vstack((a1, a2))

In [36]:
v

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [-1],
       [ 0],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [-2],
       [-3],
       [ 5]])

In [37]:
h =np.hstack((a1,a2))
h

array([[ 0, -1],
       [ 1,  0],
       [ 2,  2],
       [ 3,  3],
       [ 4,  4],
       [ 5,  5],
       [ 6, -2],
       [ 7, -3],
       [ 8,  5]])

In [38]:
c =np.concatenate((a1, a2), axis=1)
c

array([[ 0, -1],
       [ 1,  0],
       [ 2,  2],
       [ 3,  3],
       [ 4,  4],
       [ 5,  5],
       [ 6, -2],
       [ 7, -3],
       [ 8,  5]])

In [39]:
c1 =np.concatenate((a1, a2), axis=0)
c1

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [-1],
       [ 0],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [-2],
       [-3],
       [ 5]])

In [40]:
## Common Elements between two arrays
a =np.array([1, 2, 6, 8, 10])
b =np.array([2, 4, 2, 8, 4])
np.intersect1d(a, b)

array([2, 8])

In [41]:
np.where(a!=b)

(array([0, 1, 2, 4], dtype=int64),)

### Slicing of Numpy Arrays

In [42]:
mat =0.2*np.ones((45, 7), dtype =int)
mat

array([[0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2,

In [53]:
mat[0:1] =3  #column
mat

array([[3. , 3. , 3. , 3. , 3. , 3. , 3. ],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2,

In [54]:
mat[1, :] =7
mat

array([[3. , 3. , 3. , 3. , 3. , 3. , 3. ],
       [7. , 7. , 7. , 7. , 7. , 7. , 7. ],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2,

In [55]:
mat[-1, :]=5  ###last row
mat

array([[3. , 3. , 3. , 3. , 3. , 3. , 3. ],
       [7. , 7. , 7. , 7. , 7. , 7. , 7. ],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2,

In [58]:
mat[:,0] #row

array([3. , 7. , 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2,
       0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2,
       0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2,
       0.2, 0.2, 0.2, 0.2, 0.2, 5. ])

In [59]:
mat

array([[3. , 3. , 3. , 3. , 3. , 3. , 3. ],
       [7. , 7. , 7. , 7. , 7. , 7. , 7. ],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2,

In [48]:
### assign
## Create a 10 by 6 array of ones. Multiply the array by 0.04.
# change the 3rd column to 6
# modify the fourth row by 8
# modify the the las column by o.4

In [49]:
### Homework
## Create a 11 by 7 array of zeros.
# change the 5th column to 3
# modify the 6th row by 9
# modify the the last column by 8
# Merge 5th column with last column using either np.hstack or np.vstack or np.concatenate

## Identity Matrix

In [60]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])